// src/types/common.ts
// API 공통 응답 타입
// [명세 근거] API-spec §2.6 에러 응답

// ─── 성공 응답 래퍼 ───────────────────────────────────────────────────────────
// 참고: 이 프로젝트 명세는 별도 success wrapper 없이 도메인 객체를 직접 반환함
// axios 응답에서 data 필드가 곧 도메인 객체

// ─── 커서 기반 페이지네이션 ───────────────────────────────────────────────────
// [명세 근거] 대부분의 목록 API가 cursor 방식 사용
export interface CursorPageResponse<T> {
  items: T[];
  next_cursor: string | null;
}

// ─── 에러 응답 ────────────────────────────────────────────────────────────────
// [명세 근거] §2.6
// 모든 4xx/5xx 응답 형식
export interface ErrorResponse {
  code: string;
  message: string;
}

// ─── 공통 에러 코드 ───────────────────────────────────────────────────────────
export const ERROR_CODE = {
  // 인증
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  NICKNAME_ALREADY_EXISTS: 'NICKNAME_ALREADY_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  MEMBER_DEACTIVATED: 'MEMBER_DEACTIVATED',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',
  REFRESH_TOKEN_REVOKED: 'REFRESH_TOKEN_REVOKED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  // 크루
  CREW_NOT_FOUND: 'CREW_NOT_FOUND',
  CREW_NOT_RECRUITING: 'CREW_NOT_RECRUITING',
  CAPACITY_FULL: 'CAPACITY_FULL',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  ALREADY_PARTICIPATING: 'ALREADY_PARTICIPATING',
  APPLICATION_NOT_ALLOWED: 'APPLICATION_NOT_ALLOWED',
  APPLICATION_NOT_CANCELLABLE: 'APPLICATION_NOT_CANCELLABLE',
  APPLICATION_NOT_APPROVABLE: 'APPLICATION_NOT_APPROVABLE',
  APPLICATION_NOT_REJECTABLE: 'APPLICATION_NOT_REJECTABLE',
  FORBIDDEN_NOT_HOST: 'FORBIDDEN_NOT_HOST',
  FORBIDDEN: 'FORBIDDEN',
  CREW_ACCESS_DENIED: 'CREW_ACCESS_DENIED', // GET /api/feed: 미참여 크루 crew_id 지정 시
  HOST_CREW_LIMIT_EXCEEDED: 'HOST_CREW_LIMIT_EXCEEDED',

  // 미션
  MISSION_LOG_NOT_FOUND: 'MISSION_LOG_NOT_FOUND',
  ALREADY_CERTIFIED_TODAY: 'ALREADY_CERTIFIED_TODAY',   // 당일 성공 인증 중복
  CERTIFICATION_IN_REVIEW: 'CERTIFICATION_IN_REVIEW',   // 당일 PENDING_REVIEW 중복
  PARTICIPANT_NOT_ELIGIBLE: 'PARTICIPANT_NOT_ELIGIBLE', // LOCKED 아닌 참여자
  NOT_MISSION_DAY: 'NOT_MISSION_DAY',                   // SPECIFIC_DAYS 비해당 요일
  MISSION_LOG_NOT_REVIEWABLE: 'MISSION_LOG_NOT_REVIEWABLE',
  SETTLEMENT_INPUT_FROZEN: 'SETTLEMENT_INPUT_FROZEN',
  INVALID_REJECT_REASON_CODE: 'INVALID_REJECT_REASON_CODE',
  REJECT_MEMO_REQUIRED: 'REJECT_MEMO_REQUIRED',
  REJECT_MEMO_TOO_LONG: 'REJECT_MEMO_TOO_LONG',
  // 리액션
  REACTION_NOT_ALLOWED: 'REACTION_NOT_ALLOWED',     // (403) 리액션 불가 인증 로그(비참여 크루 등)
  INVALID_REACTION_TYPE: 'INVALID_REACTION_TYPE',   // (400) reaction_type 공백/길이 초과(VARCHAR(20))
  // 정산
  SETTLEMENT_NOT_FOUND: 'SETTLEMENT_NOT_FOUND',
  SETTLEMENT_NOT_RETRYABLE: 'SETTLEMENT_NOT_RETRYABLE',
  SETTLEMENT_ALREADY_SUCCEEDED: 'SETTLEMENT_ALREADY_SUCCEEDED',
  // 포인트
  INVALID_AMOUNT: 'INVALID_AMOUNT',
  INVALID_PAYMENT_ID: 'INVALID_PAYMENT_ID',
  PAYMENT_ID_REUSED_WITH_DIFFERENT_AMOUNT: 'PAYMENT_ID_REUSED_WITH_DIFFERENT_AMOUNT',
  INVALID_LIMIT: 'INVALID_LIMIT',
  INVALID_CURSOR: 'INVALID_CURSOR',
  // 알림/디바이스
  DEVICE_NOT_FOUND: 'DEVICE_NOT_FOUND',
  // AI
  AI_RECOMMENDATION_FAILED: 'AI_RECOMMENDATION_FAILED',
  AI_RESPONSE_INVALID: 'AI_RESPONSE_INVALID',
} as const;

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];
